
name: CI/CD with docker

on:
  push:
    branches: [ main ]

env:
  API_IMG: "ghcr.io/git-compendium/ci-docker/api:latest"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t "${API_IMG}" .
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push docker image
        run: docker push "${API_IMG}"
  test:
    needs: build
    runs-on: ubuntu-latest
    services:
      api:
        image: "${API_IMG}"
        ports:
          - 3001:3001
    steps:
      - uses: actions/checkout@v2
      - name: test running container
        run: |
          npm install
          npm test
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t "${API_IMG}" .
      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build docker image
        run: docker push "${API_IMG}"
